[package]
authors = ["you"]
description = "A Tauri App"
edition = "2021"
license = ""
name = "track3"
repository = ""
rust-version = "1.57"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.1", features = [] }

[dependencies]
binance-rs-async = {version = "1.3.1", features = ["wallet_api", "futures_api", "savings_api"] }
coingecko = "1.0.1"
okex = {git = "https://github.com/domechn/okex-rs.git", rev = "7126e51"}
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = {version = "1.2", features = ["http-all", "updater"] }
sqlx = { version = "0.6", features = [  "runtime-tokio-rustls", "sqlite" ] }
tokio = { version = "1", features = ["sync"] }
rust-crypto = "^0.2"
rand = "^0.3"
lazy_static = "^1.4"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[dependencies.tauri-plugin-sql]
branch = "dev"
features = ["sqlite"] # or "postgres", or "mysql"
git = "https://github.com/tauri-apps/plugins-workspace"
